---
# Source: spinnaker/charts/redis/templates/headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-redis-headless
  namespace: "default"
  labels:
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-16.13.1
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
  annotations:
    
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: redis
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: test
