---
# Source: spinnaker/charts/redis/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-redis
  namespace: "default"
  labels:
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-16.13.1
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  redis-password: "cGFzc3dvcmQ="
