---
# Source: spinnaker/charts/minio/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-minio
  labels:
    app: minio
    chart: minio-8.0.9
    release: test
    heritage: Helm
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: minio
      release: test
  template:
    metadata:
      name: test-minio
      labels:
        app: minio
        release: test
      annotations:
        checksum/secrets: cb2aebc5aeab3d2243ed0c508a9a614f3247f36dcdba968029e419e2d763db54
        checksum/config: 7c49b5ae562c59521fd324944a7649ccc825cea67c0673e21ae061584ffaf623
    spec:
      serviceAccountName: "test-minio"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: minio
          image: "minio/minio:RELEASE.2020-01-03T19-12-21Z"
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/sh"
            - "-ce"
            - "/usr/bin/docker-entrypoint.sh minio -S /etc/minio/certs/ server /export"
          volumeMounts:
            - name: export
              mountPath: /export            
          ports:
            - name: http
              containerPort: 9000
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: test-minio
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: test-minio
                  key: secretkey
          resources:
            requests:
              memory: 4Gi      
      volumes:
        - name: export
          persistentVolumeClaim:
            claimName: test-minio
        - name: minio-user
          secret:
            secretName: test-minio
