---
# Source: spinnaker/charts/redis/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: test-redis
  namespace: "default"
  labels:
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-16.13.1
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
