---
# Source: spinnaker/templates/rbac/spinnaker-sa.yaml
# In the case of a local cluster Spinnaker needs
# to be able to deploy to all namespaces in the cluster.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-spinnaker-spinnaker
  labels:
    app: "test-spinnaker"
    heritage: "Helm"
    release: "test"
    chart: "spinnaker-2.2.15"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- namespace: default
  kind: ServiceAccount
  # Clouddriver does not currently allow config of its
  # service account.
  name: default
