---
# Source: spinnaker/templates/secrets/registry.yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-spinnaker-registry
  labels:
    app: "test-spinnaker"
    heritage: "Helm"
    release: "test"
    chart: "spinnaker-2.2.15"
    component: clouddriver
type: Opaque
data:
  dockerhub: ""
